INSERT INTO drug (name, measurement, type) VALUES ('Aspirin', 100.0, 'Tablet');
INSERT INTO drug (name, measurement, type) VALUES ('Amoxicillin', 500.0, 'Capsule');
INSERT INTO drug (name, measurement, type) VALUES ('Ibuprofen', 200.0, 'Tablet');
INSERT INTO drug (name, measurement, type) VALUES ('Paracetamol', 250.0, 'Tablet');
INSERT INTO drug (name, measurement, type) VALUES ('Lisinopril', 10.0, 'Tablet');
INSERT INTO doctor (name, department, position) VALUES ('John Doe', 'Cardiology', 'Senior Physician');
INSERT INTO doctor (name, department, position) VALUES ('Jane Smith', 'Pediatrics', 'Resident');
INSERT INTO doctor (name, department, position) VALUES ('Michael Johnson', 'Orthopedics', 'Consultant');
INSERT INTO doctor (name, department, position) VALUES ('Emily Williams', 'Oncology', 'Attending Physician');
INSERT INTO doctor (name, department, position) VALUES ('David Brown', 'Neurology', 'Associate Professor');
INSERT INTO sales (name, purchase_price, selling_price) VALUES ('Product A', 10.0, 15.0);
INSERT INTO sales (name, purchase_price, selling_price) VALUES ('Product B', 20.0, 30.0);
INSERT INTO sales (name, purchase_price, selling_price) VALUES ('Product C', 8.0, 12.0);
INSERT INTO sales (name, purchase_price, selling_price) VALUES ('Product D', 50.0, 60.0);
INSERT INTO sales (name, purchase_price, selling_price) VALUES ('Product E', 25.0, 35.0);